name: Build and Test Bot
on:
  push:
    paths-ignore:
      - README.md
jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Configure NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Build and Test
        run: |
          npm ci
          npm run lint
          npm run build
      - name: Determine build pass or fail to set pretty colors in discord message
        if: always()
        run: |
          if [ ${{ failure() }} ]; then
            echo "CICD_COLOR=E01E5A" >> $GITHUB_ENV
          else
            echo "CICD_COLOR=2EB67D" >> $GITHUB_ENV
      - name: Send Discord Message with Build Status
        if: always()
        uses: slackapi/slack-github-action@v1.23.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          payload: |
            {
              "text": "${{ github.event.repository.name }} - Build and Test Bot\nOn Branch: ${{ github.ref }}\nBy: ${{ github.event.head_commit.author.name }}",
              "attachments": [
                {
                  "color": "${{ env.CICD_COLOR }}",
                  "fields": [
                    {
                      "value": "${{ job.status}}",
                      "title": "Result"
                    }
                  ]
                }
              ]
            }
