name: Build Docker
on: workflow_call
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Restore Cache
        uses: actions/cache@v3
        with:
          path: ./*
          key: ${{ github.sha }}
      - name: Build Docker Image
        run: docker build .
